spring.datasource.url=jdbc:h2:file:./data/emp;DB_CLOSE_DELAY=-1;MODE=MYSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.admin.username=${APP_ADMIN_USERNAME:admin_4827}
app.admin.password=${APP_ADMIN_PASSWORD:R4nd0m!A7}
